/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EstadosFinancieros;

import static Conexion.Conexion.conectar;
import Conexion.Conexion;
import Interfaces.EstadosFinancieros;
import Otros.Cuenta;
import Otros.PeriodoContable;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Alexis Lopez
 */
public class BalanceGeneral extends javax.swing.JFrame {
    BalanceGeneralTableModel activosTModel = new BalanceGeneralTableModel();
    BalanceGeneralTableModel pasivosTModel = new BalanceGeneralTableModel();
    BalanceGeneralTableModel capitalTModel = new BalanceGeneralTableModel();
    /**
     * Creates new form BalanceGeneral
     */
    public BalanceGeneral() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Balance General");
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/inicio.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Imagenes/cafe2.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        
        inicializarColumnas();
        
        conectar();
        
        consulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
        private void inicializarColumnas() {
        TableColumnModel tColumnModel = new DefaultTableColumnModel();
        
        for(int i = 0; i < 3; i++) {
            TableColumn col = new TableColumn(i);
            
            switch(i) {
                case 0: col.setHeaderValue("Codigo");
                    break;
                case 1: col.setHeaderValue("Nombre");
                    break;
                case 2: col.setHeaderValue("Saldo ($)");
                    break;
            }
            
            tColumnModel.addColumn(col);
        }
        tablaActivos.setColumnModel(tColumnModel);
        tablaPasivos.setColumnModel(tColumnModel);
        tablaCapital.setColumnModel(tColumnModel);
        //tablaCapital.getTableHeader().setVisible(false);
    }
    
    private void consulta() {
        double resultadoActivo = 0;
        double resultadoParticipaciones = 0;
        double resultado_debe;
        double resultado_haber;
        String fecha = "";
        String fecha1 = "";
        String diaFinal = "";
        String mesFinal = "";
        String agno = "";
        int mes = 0;
        
        try {
            String sentencia = "SELECT c.CODIGO, c.NOMBRE,c.DEBE, c.HABER, c.ESTADOFINANCIERO,c.OPERACIONENESTADO FROM cuenta c, cuentascatalogo cc WHERE ( c.cue_codigo=cc.codigo AND cc.id_tipocuenta='1' and (c.debe != 0 or c.haber != 0))";
            Statement statement = Conexion.con.createStatement();
            ResultSet resultado = statement.executeQuery(sentencia);
            
            while(resultado.next()) {
                Cuenta cuenta = new Cuenta();
                cuenta.setCodigo(resultado.getString("codigo"));
                cuenta.setNombre(resultado.getString("nombre"));
                cuenta.setSaldoDeudor(resultado.getDouble("debe"));
                resultado_debe = cuenta.getSaldoDeudor();
                cuenta.setSaldoAcreedor(resultado.getDouble("haber"));
                resultado_haber = cuenta.getSaldoAcreedor();
                    
                cuenta.setResultado(cuenta.getSaldoDeudor() - cuenta.getSaldoAcreedor());
                
                resultadoActivo += cuenta.getResultado();
                
                this.activosTModel.cuentas.add(cuenta);
            }
            tablaActivos.repaint();
            jActivo.setText("$" + Double.toString(resultadoActivo));
            
            String sentencia2 = "SELECT c.CODIGO, c.NOMBRE,c.DEBE, c.HABER, c.ESTADOFINANCIERO,c.OPERACIONENESTADO FROM cuenta c, cuentascatalogo cc WHERE ( c.cue_codigo=cc.codigo AND cc.id_tipocuenta='2' and (c.debe != 0 or c.haber != 0))";
            Statement statement2 = Conexion.con.createStatement();
            ResultSet resultado2 = statement2.executeQuery(sentencia2);
            
            while(resultado2.next()) {
                Cuenta cuenta2 = new Cuenta();
                cuenta2.setCodigo(resultado2.getString("codigo"));
                cuenta2.setNombre(resultado2.getString("nombre"));
                cuenta2.setSaldoDeudor(resultado2.getDouble("debe"));
                resultado_debe = cuenta2.getSaldoDeudor();
                cuenta2.setSaldoAcreedor(resultado2.getDouble("haber"));
                resultado_haber = cuenta2.getSaldoAcreedor();
                    
                cuenta2.setResultado(-1 * (cuenta2.getSaldoDeudor() - cuenta2.getSaldoAcreedor()) );
                
                resultadoParticipaciones += cuenta2.getResultado();
                
                this.pasivosTModel.cuentas.add(cuenta2);
            }
            tablaPasivos.repaint();
            
            Cuenta cu = new Cuenta();
            cu.setCodigo("310101");
            cu.setNombre("Capital social");
            cu.setSaldoAcreedor(0.00);
            cu.setSaldoDeudor(0.00);
            cu.setResultado(0.00);
            
            String sentencia3 = "select debe, haber from cuenta where (estadofinanciero = 1 or estadofinanciero = 2 or estadofinanciero = 4) and (debe != 0 or haber != 0)";
            Statement statement3 = Conexion.con.createStatement();
            ResultSet resultado3 = statement3.executeQuery(sentencia3);
            
            while(resultado3.next()) {
                Cuenta cuenta3 = new Cuenta();
                cuenta3.setSaldoDeudor(resultado3.getDouble("debe"));
                cuenta3.setSaldoAcreedor(resultado3.getDouble("haber"));
                    
                cuenta3.setResultado(cuenta3.getSaldoDeudor() - cuenta3.getSaldoAcreedor());
                
                if(cuenta3.getResultado() < 0) {
                    cu.setSaldoAcreedor(cu.getSaldoAcreedor() + cuenta3.getResultado() * -1);
                }
                else {
                    cu.setSaldoDeudor(cu.getSaldoDeudor() + cuenta3.getResultado());
                }
                
            }
            cu.setResultado(cu.getSaldoAcreedor() - cu.getSaldoDeudor());
            resultadoParticipaciones += cu.getResultado();
            this.capitalTModel.cuentas.add(cu);
            tablaCapital.repaint();
            jParticipaciones.setText("$" + Double.toString(resultadoParticipaciones));
            //jParticipaciones.setText("$26228.08");
            
            String sen = "select fechafinal from periodocontable order by idperiodocontable desc limit 1";
            Statement stat = Conexion.con.createStatement();
            ResultSet res = stat.executeQuery(sen);
            
            while (res.next()) {
                PeriodoContable per = new PeriodoContable();
                per.setFechaFinal(res.getDate("fechafinal"));
                fecha1 = per.getFechaFinal().toString();
                fecha = fecha1;
                diaFinal = fecha.substring(8,10);
                mesFinal = fecha.substring(5,7);
                agno = fecha.substring(0,4);
            }

            mes = Integer.parseInt(mesFinal);
            
            switch(mes) {
                case 1: mesFinal = "Enero";
                    break;
                case 2: mesFinal = "Febrero";
                    break;
                case 3: mesFinal = "Marzo";
                    break;
                case 4: mesFinal = "Abril";
                    break;
                case 5: mesFinal = "Mayo";
                    break;
                case 6: mesFinal = "Junio";
                    break;
                case 7: mesFinal = "Julio";
                    break;
                case 8: mesFinal = "Agosto";
                    break;
                case 9: mesFinal = "Septiembre";
                    break;
                case 10: mesFinal = "Octubre";
                    break;
                case 11: mesFinal = "Noviembre";
                    break;
                case 12: mesFinal = "Diciembre";
                    break;
            }
            
            lBalance.setText("Balance general al " + diaFinal + " de " + mesFinal + " de " + agno);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al recuperar los datos de la base de datos");
            ex.printStackTrace();
        }
    }
    
    private String fecha() {
        
        String fecha = "";
        String fecha1 = "";
        String diaFinal = "";
        String mesFinal = "";
        String agno = "";
        int mes = 0;
        
        try {
            String sen = "select fechafinal from periodocontable order by idperiodocontable desc limit 1";
            Statement stat = Conexion.con.createStatement();
            ResultSet res = stat.executeQuery(sen);
            
            while (res.next()) {
                PeriodoContable per = new PeriodoContable();
                per.setFechaFinal(res.getDate("fechafinal"));
                fecha1 = per.getFechaFinal().toString();
                fecha = fecha1;
                diaFinal = fecha.substring(8,10);
                mesFinal = fecha.substring(5,7);
                agno = fecha.substring(0,4);
            }

            mes = Integer.parseInt(mesFinal);
            
            switch(mes) {
                case 1: mesFinal = "Enero";
                    break;
                case 2: mesFinal = "Febrero";
                    break;
                case 3: mesFinal = "Marzo";
                    break;
                case 4: mesFinal = "Abril";
                    break;
                case 5: mesFinal = "Mayo";
                    break;
                case 6: mesFinal = "Junio";
                    break;
                case 7: mesFinal = "Julio";
                    break;
                case 8: mesFinal = "Agosto";
                    break;
                case 9: mesFinal = "Septiembre";
                    break;
                case 10: mesFinal = "Octubre";
                    break;
                case 11: mesFinal = "Noviembre";
                    break;
                case 12: mesFinal = "Diciembre";
                    break;
            }
            
           fecha = "Balance general al " + diaFinal + " de " + mesFinal + " de " + agno;
        }
        catch(SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al recuperar los datos de la base de datos");
            ex.printStackTrace();
        }
        
        return "fecha";
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaActivos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPasivos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaCapital = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jActivo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jParticipaciones = new javax.swing.JLabel();
        lBalance = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel1.setText("Balance General");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Activos");

        tablaActivos.setModel(activosTModel);
        jScrollPane1.setViewportView(tablaActivos);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Pasivos");

        tablaPasivos.setModel(pasivosTModel);
        jScrollPane2.setViewportView(tablaPasivos);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Capital");

        tablaCapital.setModel(capitalTModel);
        jScrollPane3.setViewportView(tablaCapital);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Total Activos");

        jActivo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jActivo.setText("Activos");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Total Participaciones");

        jParticipaciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jParticipaciones.setText("Participaciones");

        lBalance.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lBalance.setText("Balance General");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Atras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(350, 350, 350))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(258, 258, 258)
                        .addComponent(jActivo)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jParticipaciones)
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(lBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lBalance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jActivo)
                    .addComponent(jLabel7)
                    .addComponent(jParticipaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EstadosFinancieros menu = new EstadosFinancieros();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalanceGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jActivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jParticipaciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lBalance;
    private javax.swing.JTable tablaActivos;
    private javax.swing.JTable tablaCapital;
    private javax.swing.JTable tablaPasivos;
    // End of variables declaration//GEN-END:variables
}
