/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import static BDContabilidad.Conexion.conect;
import static BDContabilidad.Conexion.conectar;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class CrearPlanilla extends javax.swing.JFrame {

    /**
     * Creates new form CrearPlanilla
     */
    public CrearPlanilla() {
        initComponents();
        setLocationRelativeTo(null);
        DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        Calendar fechahoy = Calendar.getInstance();
        Dimension size = txtPeriodo.getCalendarPreferredSize();
        size.width += 90;
        txtPeriodo.setCalendarPreferredSize(size);
        txtPeriodo.setText(formatoFecha.format(fechahoy.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPeriodo = new datechooser.beans.DateChooserCombo();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(152, 190, 211));

        jPanel1.setBackground(new java.awt.Color(152, 190, 211));

        jLabel1.setText("Descripción:");

        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/appbar.paper.png"))); // NOI18N
        jButton4.setText("Nueva Planilla");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Periodo:");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton4)
                        .addGap(0, 175, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        Planilla2 plan = new Planilla2();
        plan.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            String descripcion = txtDescripcion.getText();
            DateFormat dffrom = new SimpleDateFormat("MM-dd-yy");
            DateFormat dfto = new SimpleDateFormat("yyyy-MM-dd");  
            Date today;
            today = dffrom.parse(txtPeriodo.getText());
            String fecha = dfto.format(today);
            
            conectar();
            String sql = "INSERT INTO planilla (descripcion, periodoplanilla, estatus) VALUES (?, ?, ?)";
            java.sql.PreparedStatement insertarPla = conect.prepareStatement(sql);
            insertarPla.setString(1, descripcion);
            insertarPla.setString(2, fecha);
            insertarPla.setBoolean(3, false);
            insertarPla.execute();
            
            int ultimoIdPlanilla = 0;
            String sqlId = "SELECT MAX(idplanilla) AS maxid FROM planilla";
            Statement ulid = conect.createStatement();
            ResultSet resultado = ulid.executeQuery(sqlId);
            while (resultado.next())
            {
                ultimoIdPlanilla = resultado.getInt("maxid");
            }
            
            String detplasql = "INSERT INTO `sic`.`detalleplanilla`(`idplanilla`,`idempleado`,`aguinaldo`,`vacacion`,`ISSS`,`AFP`,`Devengado`,`Total`,`FactorRecargo`,`FactorRecargoIneficiencia`,`GastoPorIneficiencia`)VALUES(?,?,?,?,?,?,?,?,?,?,?);";
            String empleados = "SELECT `IDEMPLEADO`,`NOMBREEMPRESA`,`NOMBREEMPLEADO`,`SALARIO`,`EFICIENCIA`,`ANIOS`,`DeptoProduccion` FROM `sic`.`empleado`;";
            
            Statement empl = conect.createStatement();
            ResultSet res = empl.executeQuery(empleados);
            Double aguinaldo, vacacion, isss, afp, devengado,
                    factorRecargo, factorRecargoInef, gastoPorInef, salarioMensual,
                    salarioCalculoGI, total;
            
            while (res.next())//Iterar por todos los empleados para crear los detalles de planilla
            {
                java.sql.PreparedStatement ppst = conect.prepareStatement(detplasql);
                ppst.setInt(1, ultimoIdPlanilla);
                ppst.setInt(2, res.getInt("IDEMPLEADO"));
                salarioMensual = res.getDouble("SALARIO");
                aguinaldo = Aguinaldo(salarioMensual, res.getInt("ANIOS"));
                vacacion = Vacaciones(salarioMensual, res.getInt("ANIOS"));
                isss = PrestacionISSS(salarioMensual);
                afp = PrestacionAFP(salarioMensual);
                //salario, int idEmpleado, String fechaFin, Boolean departamentoProduccion
                devengado = SalarioDevengado(salarioMensual, res.getInt("IDEMPLEADO"), fecha, res.getBoolean("DeptoProduccion"));
                salarioCalculoGI = salarioMensual + aguinaldo + vacacion + isss + afp;
                total = devengado + aguinaldo + vacacion + isss + afp;
                factorRecargo = FactorRecargo(salarioMensual, salarioCalculoGI);
                factorRecargoInef = FactorRIneficiencia(salarioMensual, salarioCalculoGI, res.getDouble("EFICIENCIA"));
                gastoPorInef = GastoPorIneficiencia(factorRecargo, factorRecargoInef);
                
                //aguinaldo
                //vacacion
                //ISSS
                //AFP
                //Devengado
                //Total
                //FactorRecargo, FactorRecargoIneficiencia, GastoPorIneficiencia
                ppst.setDouble(3, aguinaldo);
                ppst.setDouble(4, vacacion);
                ppst.setDouble(5, isss);
                ppst.setDouble(6, afp);
                ppst.setDouble(7, devengado);
                ppst.setDouble(8, total);
                ppst.setDouble(9, factorRecargo);
                ppst.setDouble(10, factorRecargoInef);
                ppst.setDouble(11, gastoPorInef);
                
                ppst.execute();
            }            
            
            JOptionPane.showMessageDialog(this, "Se ha creado la planilla correctamente");
            
            this.setVisible(false);
            Planilla2 plan = new Planilla2();
            plan.setVisible(true);
        }
        
        catch (SQLException e) {
            e.printStackTrace();
        } catch (ParseException ex) {
            Logger.getLogger(OrdenFab_ManoObra.class.getName()).log(Level.SEVERE, "No se pudo convertir el valor de fecha", ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPlanilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDescripcion;
    private datechooser.beans.DateChooserCombo txtPeriodo;
    // End of variables declaration//GEN-END:variables

    public Double SalarioDevengado(Double salario, int idEmpleado, String fechaFin, Boolean departamentoProduccion){
        double sal;
        double sdia;
        double salDev;
        if (!departamentoProduccion)
        {
            sal=salario;
            sdia = sal/30;
            salDev = (sdia*7)/5.5;
        }
        else
        {
            salDev = 0;
            try
            {
                String fechaIni;
                String sql = "SELECT SUM(`monto`) AS monto FROM `sic`.`orden_manoobra` WHERE `idempleado` = ? AND `fecha` BETWEEN ? AND ?;";
                java.sql.PreparedStatement summonto = conect.prepareStatement(sql);
                
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Calendar c = Calendar.getInstance();
                c.setTime(sdf.parse(fechaFin));
                c.add(Calendar.DATE, -7);  // number of days to add
                fechaIni = sdf.format(c.getTime());
                summonto.setInt(1, idEmpleado);
                summonto.setString(2, fechaIni);
                summonto.setString(3, fechaFin);
                
                ResultSet rs = summonto.executeQuery();
                while (rs.next())
                {
                    salDev = rs.getDouble("monto");
                }
            }
            catch (SQLException e) {
                e.printStackTrace();
            }
            catch (ParseException ex) {
                Logger.getLogger(OrdenFab_ManoObra.class.getName()).log(Level.SEVERE, "No se pudo convertir el valor de fecha", ex);
            }
        }   
        return salDev;          
    }
     
    public Double PrestacionISSS(Double salario){
        double sal;
        double sdia;
        double Cotizacion;
         
        sal=salario;
        sdia = sal/30;
        Cotizacion = (sdia*7)*0.075;
        return Cotizacion;          
    }
    
    public Double PrestacionAFP(Double salario){
        double sal;
        double sdia;
        double Cotizacion;
         
        sal=salario;
        sdia = sal/30;
        Cotizacion = (sdia*7)*0.0675;
        return Cotizacion;          
    }
     
    public Double Aguinaldo(Double salario, int anio){
        double sdia;
        int diasA;
        Double aguinaldo;
         
        sdia=salario/30;
         
        if ( anio > 10){
                diasA=21;
        }
        else{
                if( anio > 3){
                    diasA=19;
                }
                else {
                    if( anio >= 1){
                        diasA=15;
                    }
                    else{
                        diasA=0;
                    }
                }
        }
        aguinaldo=(diasA*sdia)/52.0;
                
        return aguinaldo;          
    }
    
    public Double Vacaciones(Double salario, int anio){
        double sdia;
        Double vacac=0.0;
         
        sdia=salario/30;
        if(anio>=1){
                vacac=((sdia*15)+(0.30*(sdia*15))+(0.1525*(sdia*15)))/52.0;
        }         
        return vacac;          
    }
    
    public Double FactorRecargo(Double SalarioMensual, Double TotalCalculado)
    {
        return TotalCalculado / SalarioMensual;
    }
    
    public Double FactorRIneficiencia(Double SalarioMensual, Double TotalCalculado, Double Eficiencia)
    {
        if (Eficiencia > 0)
            return TotalCalculado / Eficiencia / SalarioMensual;
        else return FactorRecargo(SalarioMensual, TotalCalculado);
    }
    
    public Double GastoPorIneficiencia(Double factorRecargo, Double factorRIneficiencia)
    {
        return factorRIneficiencia - factorRecargo;
    }
}
