/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Conexion.Conexion;
import static Conexion.Conexion.con;
import static Conexion.Conexion.conectar;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author chavez
 */
public class NuevoEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form NuevoEmpleado
     */
    public NuevoEmpleado() {
        initComponents();
        setLocationRelativeTo(null);

        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtEfi = new javax.swing.JTextField();
        txtAnios = new javax.swing.JTextField();
        btnAgregarEmpleado = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtSalario1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        chkDeptoProd = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel4.setText("Agregar empleado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombre ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 69, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Produccion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Años");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));
        getContentPane().add(txtNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 182, -1));

        txtEfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEfiActionPerformed(evt);
            }
        });
        getContentPane().add(txtEfi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 36, -1));

        txtAnios.setText("0");
        getContentPane().add(txtAnios, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 36, 20));

        btnAgregarEmpleado.setText("Agregar");
        btnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 210, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 210, -1, -1));
        getContentPane().add(txtSalario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 50, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Salario ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 107, -1, -1));

        chkDeptoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDeptoProdActionPerformed(evt);
            }
        });
        getContentPane().add(chkDeptoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Eficiencia");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cafe.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        // TODO add your handling code here:
        String NOMBREEMPLEADO=txtNombreEmpleado.getText();
        double SALARIO=Double.parseDouble(txtSalario1.getText());
        double EFI=Double.parseDouble(txtEfi.getText());
        int ANIOS=Integer.parseInt(txtAnios.getText());
        Boolean deptoProd = chkDeptoProd.isSelected();
        if("".equals(NOMBREEMPLEADO) || "".equals(SALARIO) || "".equals(ANIOS)){
            JOptionPane.showMessageDialog(this,"Debe llenar todos los campos");
        }else{
            conectar();
            try{
                Statement statatement = con.createStatement();
                statatement.execute("INSERT INTO empleado(NOMBREEMPLEADO, SALARIO, EFICIENCIA, ANIOS, DeptoProduccion) VALUES ('"+NOMBREEMPLEADO+"','"+SALARIO+"','"+EFI+"','"+ANIOS+"', "+deptoProd+")");
                statatement.close();
                con.close();
            }catch(SQLException e){
                System.err.println(e);
            }
            JOptionPane.showMessageDialog(this,"Empleado Agregado");
            this.setVisible(false);
            Planilla2 mp = new Planilla2();
            mp.setVisible(true);
        }
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Planilla2 pl = new Planilla2();
        pl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void chkDeptoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDeptoProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDeptoProdActionPerformed

    private void txtEfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEfiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEfiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox chkDeptoProd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAnios;
    private javax.swing.JTextField txtEfi;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtSalario1;
    // End of variables declaration//GEN-END:variables
}
